### ISSUE TITLE
Issue with reading op2 

### ISSUE THREAD

**Issue by amarpeshave** [SteveDoyle2/pyNastran#764]
[op2.zip](https://github.com/SteveDoyle2/pyNastran/files/14559896/op2.zip)
Hello,

I am trying to read-in an OP2 spit out by NX Nastran 2212. Everything works fine with pyNastran 1.3.4. After recently upgrading to 1.4.0, I get the following error:  Message='OP2' object has no attribute 'trmbu'.

I have attached the op2. 

The code snipped wherein the op2 is being read is below:
from pyNastran.op2.op2 import OP2
results = OP2()
results.read_op2(op2_FilePath) 

Cheers,
Amar

**Comment by SteveDoyle2** [comment]
That took longer than I thought it would, but it's fixed.

It was easy to update the reader to point to the correct object, but the data was not being processed in a way that played well with the rest of the code.  It's better now.

Should be in the next release.  Hopefully soon.

**Comment by SteveDoyle2** [comment]
It's been pushed to main.
